# Podfile for EdgeTAM iOS Application with PyTorch Mobile

platform :ios, '16.0'

# Disable warnings for cleaner output
inhibit_all_warnings!

target 'EdgeTAM-iOS' do
  use_frameworks!

  # PyTorch Mobile Full - Includes JIT support for TorchScript models
  # This is the full version of PyTorch for iOS with JIT compiler
  # Size: ~150 MB (larger than Lite, but includes TorchScript support)
  pod 'LibTorch', '~> 2.1.0'
  
  # Note: LibTorch includes:
  # - Core PyTorch runtime
  # - JIT compiler for TorchScript models
  # - Mobile-optimized operators
  # - Metal GPU acceleration support
  # - Quantization support
  
  # LibTorch-Lite does NOT include JIT support, so we need the full version
end

target 'EdgeTAM-iOSTests' do
  use_frameworks!
  
  # Tests don't need PyTorch Mobile
  # They can use mocks for model testing
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Enable Swift 6 concurrency
      config.build_settings['SWIFT_VERSION'] = '6.0'
      
      # Optimize for size (important with PyTorch Mobile)
      config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Osize'
      
      # Enable bitcode (if needed for App Store)
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      
      # Set deployment target
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
      
      # Disable warnings for pods
      config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
      config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
    end
  end
end
