name: EdgeTAM-iOS
options:
  bundleIdPrefix: com.edgetam
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: en
  
targets:
  EdgeTAM-iOS:
    type: application
    platform: iOS
    sources:
      - EdgeTAM-iOS
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.edgetam.EdgeTAM-iOS
      GENERATE_INFOPLIST_FILE: YES
      INFOPLIST_KEY_NSCameraUsageDescription: "EdgeTAM requires camera access for real-time video segmentation and object tracking."
      INFOPLIST_KEY_NSPhotoLibraryUsageDescription: "EdgeTAM needs photo library access to save processed videos with segmentation masks."
      INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
      INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
      INFOPLIST_KEY_UILaunchScreen_Generation: YES
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
      SWIFT_VERSION: "6.0"
      TARGETED_DEVICE_FAMILY: "1,2"
      ENABLE_PREVIEWS: YES
      DEVELOPMENT_ASSET_PATHS: "\"EdgeTAM-iOS/Preview Content\""
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
      CODE_SIGN_STYLE: Automatic
      CURRENT_PROJECT_VERSION: 1
      MARKETING_VERSION: 1.0
      SWIFT_EMIT_LOC_STRINGS: YES
    dependencies:
      - sdk: SwiftUI.framework
      - sdk: AVFoundation.framework
      - sdk: CoreML.framework
      - sdk: Metal.framework
      - sdk: MetalKit.framework
      - sdk: CoreImage.framework
      - sdk: Vision.framework
      - sdk: Combine.framework
        
  EdgeTAM-iOSTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - EdgeTAM-iOSTests
    dependencies:
      - target: EdgeTAM-iOS
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.edgetam.EdgeTAM-iOSTests
      GENERATE_INFOPLIST_FILE: YES
      SWIFT_VERSION: "6.0"
      TARGETED_DEVICE_FAMILY: "1,2"
      BUNDLE_LOADER: "$(TEST_HOST)"
      TEST_HOST: "$(BUILT_PRODUCTS_DIR)/EdgeTAM-iOS.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/EdgeTAM-iOS"
      SWIFT_EMIT_LOC_STRINGS: NO
      CURRENT_PROJECT_VERSION: 1
      MARKETING_VERSION: 1.0
      CODE_SIGN_STYLE: Automatic